services:
  django:
    container_name: django-container
    build: .
    volumes:
      - static_volume:/app/src/staticfiles
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    container_name: db-container
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    container_name: redis-container
    restart: always
    image: redis:latest

  celery:
    container_name: celery-worker-container
    build: .
    depends_on:
      - redis
      - db
    env_file:
      - .env
    working_dir: /app/src
    command: ["celery", "-A", "CVProject", "worker", "--loglevel=info"]

  nginx:
    container_name: nginx-container
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/src/staticfiles:ro
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
